# Dockerfile.nginx
FROM nginx:alpine

# Nginx 설정 복사
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 정적 파일을 위한 디렉토리 생성
RUN mkdir -p /usr/share/nginx/html/_next/static
RUN mkdir -p /usr/share/nginx/html/public

# 디버깅을 위한 도구 설치
RUN apk add --no-cache curl vim

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]